### ISSUE TITLE
Does the environment support an order queue (just like in original game?)

### ISSUE THREAD

**Issue by 51616** [rosewang2008/gym-cooking#5]
IIUC, the environment support only one recipe for one layout.
So my goal is to have multiple recipes for one layout in combination with order queue that prioritize earlier order with higher reward.

Is there a specific file that support this feature? If not is there a recommended way to implement this?

**Comment by rosewang2008** [comment]
Hi! The environment does support more than one recipe, for example [as described here in the documentation](https://github.com/rosewang2008/gym-cooking/blob/main/docs/design.md#customize-environments). 

It's as easy as just specifying another recipe! Another example is one I just created with two tomato recipes. The file looks like this, with two `SimpleTomato` recipes listed as described in the documentation.

![Screen Shot 2021-01-13 at 7 50 06 AM](https://user-images.githubusercontent.com/26608062/104475439-f54d0e80-5573-11eb-94cc-74823b91e6ff.png)

When you run the appropriate command, the expected result is that you should see the subtasks contain two copies of the tomato recipe like this:

![Screen Shot 2021-01-13 at 7 46 15 AM](https://user-images.githubusercontent.com/26608062/104475571-1d3c7200-5574-11eb-8084-4e15fe42a275.png)

In our setting, we don't have a notion of "higher" vs. "lower" priority recipes. One way you could integrate that is by defining the environment reward to reflect those priorities; as of right now, environment reward is simply 1 if the agents complete the recipes, and 0 otherwise (rf [here](https://github.com/rosewang2008/gym-cooking/blob/main/gym_cooking/envs/overcooked_environment.py#L245-L246)).

You could also add in priority information in the `info` variable returned by the environment (depending on what information you'd like the environment to pass to the agents). That can be defined [here](https://github.com/rosewang2008/gym-cooking/blob/main/gym_cooking/envs/overcooked_environment.py#L213-L214).

Let me know if that helps you get started!

**Comment by 51616** [comment]
@rosewang2008 Thank you for the informative answer! I think this definitely will help me get started adding this feature.
